server.port=8080
spring.application.name=logguard-ai
spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.database=logguard

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

alert.receiver.email=${ALERT_TO}