server.port=8080
spring.application.name=logguard-ai
spring.data.mongodb.uri=mongodb+srv://kodalisuchitrakamala_db_user:9uygYTr57YU6odBh@ac-si41mhg.smypq4y.mongodb.net/logguard?retryWrites=true&w=majority&appName=LogGuard-AI
spring.data.mongodb.database=logguard
