import axios from 'axios';
const BASE_URL = "https://logguard-mern-api.vercel.app/api";
const api = axios.create({ baseURL: BASE_URL, timeout: 30000 });
api.interceptors.request.use((req) => {
  const token = localStorage.getItem('token');
  if (token) req.headers.Authorization = `Bearer ${token}`;
  return req;
});
export const login = (data) => api.post('/auth/login', data);
export const register = (data) => api.post('/auth/register', data);
export const getCurrentUser = () => api.get('/auth/me');
export const MERN_API = api;
export const JAVA_API = api;
export default api;
export const uploadLogFile = (fd) => api.post('/upload', fd, { headers: { 'Content-Type': 'multipart/form-data' } });
export const getAnalytics = () => api.get('/analytics');
export const getLatestLogs = () => api.get('/logs/latest');
export const getLogs = (p) => api.get('/logs', { params: p });
export const getNotifications = () => api.get('/notifications');
export const analyzeLogsAI = (logs) => api.post('/ai/analyze', { logs });
export const checkMernHealth = () => api.get('/health');
